### ISSUE TITLE
m4a seems to fall back to flash when using setFile()

### ISSUE THREAD

**Issue by sml-khamilton** [frankyghost/projekktor#1]
I have an .m4a audio file which plays 'correctly' in chrome if I hard code it into the playlist in the projekktor config. If I use the setFile() function however, it seems to fall back to flash, and doesn't play at all (which is probably a separate issue)

here's a sample debug output:

when hardcoded:
0: "Update: 'state"
1: "http://myserver.local/Asha.m4a"
2: "AUDIO"
3: "PLAYING"

when using setFile()
0: "Update: 'state"
1: "http://myserver.local/Asha.m4a"
2: "AUDIOFLASH"
3: "PLAYING"

(I don't want to make this message painfully long, so if you need more info please let me know)

**Comment by frankyghost** [comment]
Thx for reporting this. Will try to reproduce it. Please stay tuned.

**Comment by sml-khamilton** [comment]
setting mp4 and m4a to video/mp4 seems to fix this issue.
