### ISSUE TITLE
The site seems down

### ISSUE THREAD

**Issue by jmontoyaa** [frankyghost/projekktor#2]
Links are dead:

http://www.projekktor.com/docs.php
http://www.projekktor.com/compatibility.php
http://www.projekktor.com/demo.php

The project is still there?

**Comment by frankyghost** [comment]
Thanx for reporting this.
D´oh, the .htaccess was accidentally  messed up.
Sorry about that.

**Comment by jmontoyaa** [comment]
Nice!!
