### ISSUE TITLE
Provide projekktor via bower.io

### ISSUE THREAD

**Issue by Tatort79** [frankyghost/projekktor#25]
Hi Sascha,

i would be great if you can provide the projekktor player via bower (http://bower.io/#registering-packages)

Thanks,
 Thomas

**Comment by paxal78** [comment]
i'm agree. 
thanks

**Comment by rvullriede** [comment]
I'd also like this very much!

**Comment by paulinhoAlmeida** [comment]
this project is now registered in bower

**Comment by rwlodkowski** [comment]
Thanks for the registration :)

**Comment by zd-dalibor** [comment]
Yes is registered but we must manually build dis files. Dist folder does not have projekktor.js. I must add all js file from to src folder to have worked version of projekktor if I don't wont to build dist files manually or to download package from projekktor site.
