### ISSUE TITLE
Which of the StrobeMediaPlayback.swf should I include by default?

### ISSUE THREAD

**Issue by mdempfle** [frankyghost/projekktor#39]
Which of the 4 StrobeMediaPlayback.swf files do I need to include? I want to add this to my page where users can upload content. 
Of do yI need all 4 and the StrobeMediaPlayback.swf does load the other ones when needed?

Thanks, Michael

**Comment by rwlodkowski** [comment]
@mdempfle, you need only one of the SMP swf files, depending on your needs. File names are quietly selfdescribing, so:

StrobeMediaPlayback.swf - SMP without any 3rd party plugins
StrobeMediaPlayback_hls.swf - SMP with statically compiled HLS plugin
StrobeMediaPlayback_mss.swf - SMP with statically compiled Microsoft Smooth Streaming plugin
StrobeMediaPlayback_hls_mss.swf - SMP with statically compiled both HLS & MSS plugins

So if you don't need HLS and/or MSS support you could feed projekktor with clean StrobeMediaPlayback.swf. That's the base functionality.

Btw. if you need to compile your own SMP for projekktor you can find it sources here:
https://github.com/fixedmachine/projekktor-StrobeMediaPlayback

Best
fixedmachine

**Comment by mdempfle** [comment]
Great,

Thanks for the quick response.

I only want to support mp4, webm and ogv right now.
So the normal StrobeMediaPlayback.swf should work fine for me.

And just to be sure. I don't need and flv file as fallback as the mp4 
file is used here?

Thanks, Michael

Am 27.05.2014 16:57, schrieb Radosław Włodkowski:

**Comment by rwlodkowski** [comment]
@mdempfle, there is no need for flv files when you're using mp4. 

You can even stick only to mp4s for most desktop browsers and whole range of mobile browsers with native HTML5 <video> model and use flash fallback for browsers which don't support mp4 and/or HTML5 <video>.

**Comment by mdempfle** [comment]
So I don't even need webm?
As I have unserstood this I need mp4 and webm/ogv for HTML5 to support 
most browsers. And then the StrobeMediaPlayback.swf (which uses the mp4 
file)  for e.g. IE.

Best, Michael

Am 27.05.2014 17:17, schrieb Radosław Włodkowski:

**Comment by rwlodkowski** [comment]
If you wan't to use only HTML5 native <video> support on any browser which supports <video> than yes, you should provide: mp4, webm, ogv files to cover all of them.

But if you don't care if your video will be played by browser native <video> tag or by flash plugin you can stick to mp4 format with projekktor.

**Comment by mdempfle** [comment]
Great,

This is good for my users. Than I can tell them that they need mp4 and 
the other ones would than only be needed to support native HTML5 playback.

Am 27.05.2014 17:29, schrieb Radosław Włodkowski:

**Comment by rwlodkowski** [comment]
Yep. Can I close this ticket?
