### ISSUE TITLE
Projekktor loader not disappears when song is playing

### ISSUE THREAD

**Issue by jeanAMB** [frankyghost/projekktor#41]
Actual behaviour:
Very often projekktor loader is still visible when song is playing.
When this problems occurs, player doesn't play the next song. No reaction when song is finished

**Comment by rwlodkowski** [comment]
@jeanAMB, could you provide more info? Your projekktor config, what files are you trying to play and your system/browser spec.

If you could setup demo example of that behaviour it would be nice.

**Comment by jeanAMB** [comment]
Sorry for late but it seems that the problem doesn't appears anymore.
