### ISSUE TITLE
Incompatibility with JQuery 1.10.x

### ISSUE THREAD

**Issue by TobiasKrais** [frankyghost/projekktor#49]
When using JQuery 1.10.x the volume slider can only be dragged, not clicked. Also the video timeline can no more be clicked. Here is an example page:
http://www.kaltenbach.com/en/powerful-solutions/media/videos/virtual-plants/

Could be my customer would pay for fixing this issue.

**Comment by rwlodkowski** [comment]
That's definitely not a problem with jQuery, but with the slider itself. It was repaired in: #34 you can merge it yourself or wait for the next release.

**Comment by rwlodkowski** [comment]
@TobiasKrais, btw. on that site is unknown mod of projekktor in unknown version, so I can't really help you in this situation.
