### ISSUE TITLE
IE7: useful error message when flash is not available

### ISSUE THREAD

**Issue by fuddl** [frankyghost/projekktor#7]
would be nice to have an error message that tells the user ether to update the browser or to install flash (like in the good old days) instead of:

> Sorry, your browser does not support the media format of the requested file.

**Comment by frankyghost** [comment]
All error messages can be customized via player config.(http://www.projekktor.com/docs/configuration#messages_objectsee_below). To make error texts  context sensitive however isn´t that trivial and not really necessary I think.
